- package.json
- src/Button/Button.scss
- Adds basic button partial to test integration
cc/ @saralohr @williamdingwall
> Configures package.json for npm consumption

- src/base/config.scss
- src/components/index.scss
- src/components/step-nav.scss
- src/index.scss
- src/tools/index.scss
- src/tools/mixins.scss
Adding Step Nav component from registration and updating to make more easily composable..
for reference : https://github.com/teamsnap/ui-patterns/pull/1
> first pass on StepNav

- .gitignore
- CONTRIBUTING.md
- README.md
- package.json
- sass-lint.yml
- Configures and publishes to npm under teamsnap org 🎉  https://www.npmjs.com/package/@teamsnap/teamsnap-ui 
- Configures `sass-lint` and starter rules config 
- Configures npm scripts for testing / publishing updates fixes #3
> Npm package updates

- src/base/config.scss
- src/components/grid.scss
- src/components/index.scss
- src/teamsnap-ui.scss
- src/utils/flex.scss
- src/utils/index.scss
- src/utils/size.scss
+ Updates comment style so comments aren't output in CSS
+ Make spacing more consistent in `config.scss`
+ Adds `Grid` component, `size` utilities, and `flex` utilities borrowed from SUITCSS with a few exclusions, and Sass-ified.
Documented in `ui-patterns`: https://github.com/teamsnap/ui-patterns/pull/7
> Add flex, grid and size

- src/base/config.scss
- src/utils/size.scss
> Add breakpoint variables, responsive sizing and reduced fractions

- src/components/step-nav.scss
> Updating the step nav to support longer text

- package.json
- src/components/Button.scss
The variable name in the button component should be `$cu-background` instead of `cui-background`
> bugfix-variable-name

- src/components/ButtonGroup.scss
- src/components/index.scss
> Add button group component

- src/components/Checkbox.scss
- src/components/SelectBox.scss
+ Add focus state to `Checkbox` control
+ Attach `:disabled` state to `Checkbox-input`
+ Modify `SelectBox` to remove JS dependency
+ Simplify by placing all visual styles on `SelectBox-options`
> Update custom form controls

- src/base/config.scss
- src/base/functions.scss
- src/base/mixins.scss
- src/components/Toggle.scss
- src/components/step-nav.scss
condensing work from these two PRs..
https://github.com/teamsnap/teamsnap-ui/pull/23
https://github.com/teamsnap/teamsnap-ui/pull/24
..and wrapping up
> Refactor media query mixins to be dynamic

- src/base/config.scss
- src/components/Panel.scss
- src/teamsnap-ui.scss
- src/utils/border.scss
- src/utils/display.scss
- src/utils/flex.scss
- src/utils/index.scss
- src/utils/size.scss
- src/utils/space.scss
- src/utils/text.scss
+ Extends `.Panel` component to account for table-like layouts and responsive layouts
+ Add base and responsive utilities for text, display, space and borders
> Responsive Panel and utilities

- src/components/SummaryList.scss
I think the problem was from this bad variable name which somehow didn't make it into master.
> variable name fix for summary list

- src/components/Input.scss
I have a few questions in the scss comments about this. I did the styling and created some elements in the components for errors/feedback but am wondering if I should create a form component so it has examples of all possiblities (option/checkbox/radio/etc.) Also had some questions I posed to slack about the use of svg icons within the css.
> DES-99 initial styling for errors

- src/utils/border.scss
- src/utils/display.scss
- src/utils/flex.scss
+ Update border scss loop so there is not repetition of u-border and u-borderNone
+ Move u-flex to display so that it can be used in succession with other responsive display utilities
> Update border, flex and display utilities:

- src/components/Panel.scss
+ Include styles for header button so header height doesn't increase when button is added
+ Include flex properties on rows with cells so these don't always have to be added via markup
+ Write better documentaion
> Update Panel CSS

- src/base/typography.scss
- src/components/grid.scss
- src/config/config.scss
+ Make grid 100% so it fills parent flex elements
+ Move type variables to config for ease of single importc
> Edits ahead of node module bump in LFE:

- package.json
Changes include:
+ Add ProgressBar and ListSummary components
+ Update Panel component to accommodate table layouts and add small screen options
+ Update flex utility so that it can be used in progression with other responsive display utilities
+ Add error states for form controls
+ Modify custom form controls to add focus states and remove JS dependency from custom select
+ Add new location and lock icons
+ Update StepNav for use with SVG icons
+ Reorganize base SCSS files for easier imports and separation from Classic CSS
Some of these changes require updates to `league-frontend`. Those are being addressed here:
https://github.com/teamsnap/league-frontend/pull/371
> NPM major version release 1.0.0

- src/components/FormGroup.scss
- src/components/Input.scss
- src/components/InputGroup.scss
- src/components/SelectBox.scss
- src/components/index.scss
- src/utils/space.scss
+ Refactor `Input` and add `FormGroup` and `InputGroup` for more flexible form handling
+ Include `Checkbox` and `SelectBox` in form error styles
+ Add additional spacing classes
> Update form components

- .gitignore
- README.md
- config.js
- gulpfile.js
- package.json
- src/fonts/museo.scss
- src/fonts/ss-pika.scss
- src/themes/blue-steel.scss
- src/themes/care-bear.scss
- src/themes/christmas-sweater.scss
- src/themes/custom-aquablue.scss
- src/themes/custom-black.scss
- src/themes/custom-blue.scss
- src/themes/custom-darkblue.scss
- src/themes/custom-darkgreen.scss
- src/themes/custom-darkred.scss
- src/themes/custom-goldenyellow.scss
- src/themes/custom-gray.scss
- src/themes/custom-green.scss
- src/themes/custom-leafgreen.scss
- src/themes/custom-lemonyellow.scss
- src/themes/custom-lightblue.scss
- src/themes/custom-orange.scss
- src/themes/custom-pink.scss
- src/themes/custom-purple.scss
- src/themes/custom-red.scss
- src/themes/maple-leaf.scss
- src/themes/portland-oregon.scss
- src/themes/ranger-smith.scss
- src/themes/up-beet.scss
This is a first pass at prepping TeamSnap-UI for publishing CSS to CDN.
What I did:
+ Added color themes from Classic
+ Set up a bunch of Gulp tasks to build our CSS
+ Updated font paths (I thought maybe we could publish fonts from here after all... the app will only download the font the first time it gets the request I think... otherwise it will use the one it already has - need to check this)
> Add themes and initial gulp tasks

- .eslintrc
- package-lock.json
- package.json
- src/js/components/Cell/Cell.js
- src/js/components/FieldLabel/FieldLabel.js
- src/js/components/InputControl/InputControl.js
- src/js/components/StepNav/StepNav.js
- src/js/components/StepNav/index.js
- src/js/components/SummaryList/SummaryList.js
- src/js/components/SummaryList/index.js
- src/js/index.js
Add SummaryList Component - https://teamsnap-ui-patterns.netlify.com/patterns/components/summary-list.html
* Note this is branched off of the 'StepNav' branch, this should follow that PR.
> Summary list component

- package.json
> Add Popup styles, and Button status, square modifier styles

- package.json
Moving `lodash` from devDependencies to dependencies.
> Update lodash dep location

- package-lock.json
- package.json
- src/js/components/Button/Button.js
- src/js/components/ProgressBar/ProgressBar.js
- src/js/components/RadialProgress/RadialProgress.js
- src/js/components/RadialProgress/index.js
- src/js/index.js
Adds react RadialProgress component and updates PropressBar components
> Progress bars

- src/css/base/typography.scss
- src/css/components/Button.scss
- src/css/components/Input.scss
- src/css/components/Panel.scss
- src/css/components/Popup.scss
- src/css/components/Tooltip.scss
- src/css/config/config.scss
- Modify links color variable to match what is used in themes and Classic
- Update button colors to work with themes
- Update Panel and Popup colors to work with themes
> Modify component colors to fix themes

- .sass-lint.yml
- package-lock.json
- package.json
- src/js/components/InputControl/InputControl.js
- Updates sass linter to report as warnings instead of errors
- Fixes js lint error 
- updates packages to try to fix vulnerability warning
- Adds `files` entry to package.json to explicity include /dist into packaging
> Publishing issues

- CHANGELOG.md
- package-lock.json
- package.json
- src/js/components/Table/Table.js
Updates the table component to receive new props.
> Table Component Updates

- CHANGELOG.md
- package.json
- src/css/components/Button.scss
- src/css/components/Input.scss
- src/css/components/SelectBox.scss
- Add large modifiers for `Input` and `Select`
- Update large modifier for `Button`  (this currently isn't being used anywhere as far as I know)
> Add large styles for input, select and button

- package-lock.json
- package.json
- src/css/components/SummaryList.scss
- src/css/config/config.scss
- src/css/utils/color.scss
- src/js/components/SummaryList/SummaryList.js
I updated the SummaryList component and took a stab at adjusting some of the styles to better suite some recent designs.   If this went in the wrong direction I can remove the styles and adjust the component accordingly.  just thought I would take a stab at it.
Below is the adjustments that were made.  Some smaller spacing and adjustments to border-size if no heading is present as well as adding some style around the footer. 
I've ensured @williamdingwall's feedback has beed added and I updated the prop behavior to provide both styles of footer text.
> Adjust SummaryList Component & Styles

- CHANGELOG.md
- package-lock.json
- package.json
- src/js/components/SummaryList/SummaryList.js
Can a get a quick 👍  on this.  dumb typo.
> Bugfix summarylist

- CHANGELOG.md
- CONTRIBUTING.md
- package.json
- src/css/components/Tooltip.scss
minor CSS update to the tooltip to make it more flexible
> bug fix on tooltip css

- CHANGELOG.md
- CONTRIBUTING.md
- package.json
- src/css/components/Tooltip.scss
looks like you can't manually update?
> Package bugfix

- README.md
missing components, utilities, and documentation
> updating readme with CSS tasks

- CHANGELOG.md
- package.json
- src/css/components/Popup.scss
- src/js/components/Table/Table.stories.js
- adding a focus state and focus within state for .Popup--hover modifier
- adding table knobs to storybook
- updating change log to better reflect recent work
> Popup focus state & Table Knobs

- src/js/components/RadialProgress/RadialProgress.stories.js
> Add Radial Progress to the storybook

- .storybook/config.js
- .storybook/storybook.scss
- src/js/components/Icon/Icon.stories.js
- src/js/components/ProgressBar/ProgressBar.stories.js
- src/js/components/RadialProgress/RadialProgress.stories.js
- Add padding to all stories (thanks @williamdingwall )
- Add select knobs to Icons for choosing icon, and adding mods for size and color:
> Storybook icons

- src/js/components/Select/Select.stories.js
This adds a storybook element for the Select component.
It has two stories:
* Default, which only has a standard select box with three options
* Alternates, which has a large select box, and a select box with one disabled option
> added select stories.js

- CHANGELOG.md
- package.json
- src/css/components/Panel.scss
- src/js/components/Panel/Panel.js
- src/js/components/Panel/Panel.stories.js
- src/js/components/PanelHeader/PanelHeader.js
adding a panel story and panelImage proptype
> Panel story

- CHANGELOG.md
- package.json
it's a weird issue where the package content is behind the version
> Package bump

- src/js/components/PanelHeader/PanelHeader.js
- src/js/components/ProgressBar/ProgressBar.stories.js
- src/js/components/RadialProgress/RadialProgress.stories.js
- src/js/components/StepNav/StepNav.stories.js
- src/js/components/Table/Table.js
- src/js/components/Table/Table.stories.js
I came in to modify the table so that it could render JSX elements instead of just strings and was pleasantly surprised to see that it already worked that way! I did end up formatting the table file as well as adding a new storybook data set that showcases using JSX instead of strings.
> Add in JSX rendering story for table

- src/js/components/Popup/Popup.stories.tsx
- src/js/components/Popup/PopupAction.tsx
- src/js/components/Popup/PopupConfirm.tsx
- src/js/components/Popup/index.ts
- src/js/index.ts
https://teamsnap.atlassian.net/secure/RapidBoard.jspa?rapidView=242&modal=detail&selectedIssue=TNL-1880
Organization is using an existing popup that is merged into TeamSnap UI in this PR called PopupActions. This also includes PopupConfirm, which presents the user with a yes or no confirm option, like in https://teamsnap-ui-patterns.netlify.com/patterns/components/popup.html#overlay
> Add in components for PopUp buttons

- CHANGELOG.md
- package-lock.json
- package.json
- src/js/components/Table/Table.stories.tsx
- src/js/components/Table/Table.tsx
- Modified the prop type requirements for the Table component's column object's label.
- Update the storybook to capture that example.
This change fixes an issue that caused console errors to be thrown when providing JSX to a table's column's label.
This has been tested via modifying the tables storybook file and ensuring that no further console errors are thrown.
This is a backwards compatible change and should probably be treated as a patch.
> Update the proptypes of the table's column's label to reflect reality

- CHANGELOG.md
- package-lock.json
- package.json
- src/js/components/Table/Paginated/PaginatedTable.tsx
Fix broken type signature by adding index to MapDataToRow callback
✅ Closes: #264
> fix: 🐛 Add index to mapDataToRow callback

- src/css/components/Feedback.scss
Trying to capture the style for this feedback (https://www.figma.com/proto/GNPNI5QlQy274h6nUAvePh/Checkout-Credits?node-id=73%3A145&scaling=min-zoom) when the child toggle is "off." I called it "Feedback--disabled" but Im happy to find a better name for it.
> Add in disabled styles for feedback

- src/js/components/Table/Paginated/PaginatedTable.tsx
> Update Bulk Action states for paginated table

- CHANGELOG.md
- package-lock.json
- package.json
- src/js/components/Table/Paginated/BasicSearch.tsx
- src/js/components/Table/Paginated/PaginatedTable.stories.tsx
- src/js/components/Table/Paginated/PaginatedTable.tsx
- src/js/components/Table/Paginated/PaginationButtons.tsx
> minor style updates for paginated table

- src/js/components/Tabs/Tabs.stories.tsx
- src/js/components/Tabs/Tabs.tsx
- src/js/components/Tabs/index.ts
- src/js/index.ts
Add in a React component for managing tabs :)
> Add in tabs component

- CHANGELOG.md
- package-lock.json
- package.json
- src/css/components/Avatar.scss
- src/css/components/index.scss
- src/js/components/Avatar/Avatar.stories.tsx
- src/js/components/Avatar/Avatar.tsx
- src/js/components/Avatar/index.ts
- src/js/components/Tabs/Tabs.stories.tsx
- src/js/components/Tabs/Tabs.tsx
- src/js/components/Tabs/index.ts
- src/js/index.ts
Add in a React component to help with building "Avatars". These are needed in Organizations, and I imagine we're using circular images elsewhere, too.
> Add in Avatar component

- CHANGELOG.md
- package-lock.json
- package.json
- src/css/components/Avatar.scss
- src/js/components/Avatar/Avatar.stories.tsx
- src/js/components/Avatar/Avatar.tsx
- src/js/components/Tabs/Tabs.tsx
Also fix an issue where images smaller than the avatar size wouldn't upscale properly.
> Update Avatar and Tabs to not require Mods

- .storybook/config.js
- .storybook/storybook.scss
- src/css/components/ButtonGroup.scss
- src/css/components/Panel.scss
- src/css/utils/color.scss
- src/js/components/Pagination/PaginationButtons.tsx
- src/js/components/Panel/Panel.stories.tsx
- src/js/components/Table/Table.stories.tsx
- src/js/components/Table/Table.tsx
Migrate Panels (easy) and Table (rough) over to v4. Additionally, convert the table component to a function component and drastically simplify (in my opinion) the table logic.
> Panels and tables

- src/css/components/Panel.scss
Hover transitions and minor adjustments to table colors.
> V4 table transitions

- src/css/components/Avatar.scss
- src/css/components/Nav.scss
- src/css/components/Tabs.scss
- src/css/components/index.scss
- src/js/components/Avatar/Avatar.tsx
- src/js/components/Nav/Nav.stories.tsx
- src/js/components/Nav/Nav.tsx
- src/js/components/Nav/index.ts
Will have to circle back to this for more treatment on the Nav Header piece when we figure out exactly what we want to do there, but I think the rest is pretty solid and good to go! Will tag a few people with react experience to get their opinions on the way the component works.
@dbhaasis @stevencwarren @wiseemily88, can I get any feedback on the demo implementation in the storybook? Does that seem like an okay way to use this component? Is it confusing? Would you expect it to be configured and used differently?
> Left Navigation

- CHANGELOG.md
- package-lock.json
- package.json
Need a changelog and version bump to publish a previous PR (#538)
> Update changelog for 3.10.3

- CHANGELOG.md
- package-lock.json
- package.json
- src/js/components/Pagination/PaginationButtons.tsx
- src/js/components/Table/Paginated/PaginatedTable.stories.tsx
- src/js/components/Table/Paginated/PaginatedTable.tsx
- src/js/utils/placement.ts
> Allow pagination to be displayed below the paginated table

- CHANGELOG.md
- package-lock.json
- package.json
- src/js/components/Table/Paginated/PaginatedTable.tsx
Exposes the enum type for pagination placement prop.
> Expose PaginatedPlacement on PaginatedTable

- package.json
- src/js/components/Table/Paginated/PaginatedTable.tsx
https://user-images.githubusercontent.com/81430847/113784358-89052580-96f2-11eb-9e42-2a405289d3d4.mov
https://teamsnap.atlassian.net/browse/SO-3701
> Allow indeterminate state on select-all checkbox

- CHANGELOG.md
- package.json
Forgot to update versions before suqashing last commit
> Updating versions

- src/js/components/ToggleCheckboxList/ToggleCheckboxList.stories.tsx
- src/js/components/ToggleCheckboxList/ToggleCheckboxList.tsx
Fixing issue with typescript props being passed in
> Fix typescript data structure

- CHANGELOG.md
- package.json
- src/css/components/Pill.scss
- src/css/components/index.scss
- src/js/components/Panel/Panel.stories.tsx
- src/js/components/Pill/AttachmentPill/AttachmentPill.tsx
- src/js/components/Pill/AttachmentPill/index.tsx
- src/js/components/Pill/CheckboxPill/CheckboxPill.tsx
- src/js/components/Pill/CheckboxPill/index.tsx
- src/js/components/Pill/Pill.stories.tsx
- src/js/components/Pill/Pill.tsx
- src/js/components/Pill/index.tsx
Creating a base pill component as well as more complicated alternative components that use the base pill component
> So 4418 create pill components

- CHANGELOG.md
- package.json
- src/js/components/ListToggle/ListToggle.tsx
- src/js/components/Pill/AttachmentPill/AttachmentPill.tsx
- src/js/components/Pill/CheckboxPill/CheckboxPill.tsx
- src/js/components/Pill/Pill.tsx
- src/js/components/Tag/Tag.tsx
- src/js/components/ToggleCheckboxList/ToggleCheckboxList.tsx
Needed to import components using `import * as React from 'react'` rather than just `import React from 'react'`
> Importing react properly

- CHANGELOG.md
- package.json
- src/js/components/Tabs/Tabs.tsx
- src/js/components/ToggleCheckboxList/ToggleCheckboxList.tsx
Fixing warnings for missing unique key prop for some components that iterate through data
> Fix unique key prop errors

- CHANGELOG.md
- package.json
- src/css/components/Panel.scss
Updating active rows to have a light grey/bluish shade like in the mockups
Before
After
> Updating active row background color for ToggleCheckboxList component

- src/js/components/ToggleCheckboxList/ToggleCheckboxList.stories.tsx
- src/js/components/ToggleCheckboxList/ToggleCheckboxList.tsx
Adding a select all function to component so we can reference it with a React Ref and be able to use a 'select all' button call from an outside component
> Adding a select all function to component

- CHANGELOG.md
- package.json
- src/js/components/ToggleCheckboxList/ToggleCheckboxList.stories.tsx
- src/js/components/ToggleCheckboxList/ToggleCheckboxList.tsx
I was handling state internally for this component and it should have been created so that it accepts both data and state from a parent element
> Lifting state for ToggleCheckboxList component

- package.json
- src/js/components/ToggleCheckboxList/ToggleCheckboxList.stories.tsx
- src/js/components/ToggleCheckboxList/ToggleCheckboxList.tsx
Changing the recipient list to use the division id as part of the logic to be able to determine what rows are active, so that we can later send those division id's back to the back end
> Updating division list

- package.json
- src/css/components/ToggleCheckboxList.scss
- src/css/components/index.scss
- src/js/components/Modal/Modal.stories.tsx
- src/js/components/Modal/Modal.tsx
- src/js/components/ToggleCheckboxList/ToggleCheckboxList.stories.tsx
- src/js/components/ToggleCheckboxList/ToggleCheckboxList.tsx
Making multiple UI enhancements to `Modal` as well as `ToggleCheckboxList`
* collapsed default state
* error state
*default modal has no action
> Toggle checkbox list and modal improvements

- .github/workflows/main.yml
- CHANGELOG.md
- CONTRIBUTING.md
- package-lock.json
- package.json
Add audit to CI and fix several vulnerabilities.
Fixes:
* CVE-2021-27515
* CVE-2021-23337
* CVE-2020-7733
* CVE-2021-27292
> Add audit to CI

- package.json
- src/css/components/ToggleCheckboxList.scss
- src/js/components/ListToggle/ListToggle.tsx
- src/js/components/ToggleCheckboxList/ToggleCheckboxList.tsx
Adding UI enhancements...
* Update `ListToggle` to display the arrow properly based on open or closed state
* Update `ToggleCheckboxList` to highlights panel header when we selected all on that header
> UI enhancements for SO-4640

- .github/workflows/main.yml
- package-lock.json
- package.json
Fixing Issues I introduced in #652:
* clean npm install, right now master is ending up with a diff
* Fix the `npm run build:js` step by downgrading react storybook (re-opens 2 high severity vulnerabilitie)
* Disable the audit, this PR does leave 3 high severity vulnerabilities in total
> Clean npm install

- CHANGELOG.md
- package-lock.json
- package.json
- src/css/fonts/museo.scss
- src/css/fonts/ss-pika.scss
> Move asset location

- package.json
- src/js/components/ToggleCheckboxList/ToggleCheckboxList.stories.tsx
- src/js/components/ToggleCheckboxList/ToggleCheckboxList.tsx
* Adding ability to view recipient list with the new flat list program/ seasons structure
> Adding ability to display new flat-list division program structure

- package-lock.json
- package.json
- src/js/components/ToggleCheckboxList/ToggleCheckboxList.tsx
Updating alpha to this
to mimic this...
> Updating alpha order

- package.json
- src/js/components/Tag/Tag.tsx
- src/js/components/ToggleCheckboxList/ToggleCheckboxList.stories.tsx
- src/js/components/ToggleCheckboxList/ToggleCheckboxList.tsx
Adding the archive option to the component to be able to display archived seasons
> Adding archive option to component

- src/js/components/Field/Field.stories.tsx
- src/js/components/Field/Field.tsx
Clean up the InputProps in the Field Component
Closes #613
> Clean up field component InputProps

- package-lock.json
- src/css/components/SelectBox.scss
Small PR to get us more in-line with the v4 styles for this dropdown. We are looking at implementing a fully custom select for future work, but this will get us pretty close to the v4 design for now.
Probably not critical enough to release this as is, so we can merge it and it can piggyback on the next release.
> Remove select mini border

- src/css/components/Checkbox.scss
- src/js/components/Field/Field.stories.tsx
- src/js/components/Field/Field.tsx
Add support for Radio Buttons via the Field component; adjust styles so that the radio button looks more like it's intended to with V4.
> Add a new radiobutton functionality

- package.json
- src/css/components/Button.scss
- src/js/components/Button/Button.stories.tsx
- src/js/components/Button/Button.tsx
- src/js/components/Modal/Modal.stories.tsx
- src/js/components/Modal/Modal.tsx
- Added `type=button` to close button of Modal component so that it does not submit form when closing modal. 
- Made modifications to `Button--text` utility class to make button look more like a text link.
> minor fixes to text button and modal component

- package.json
- src/css/components/Breadcrumbs.scss
- src/css/components/index.scss
- src/js/components/Breadcrumbs/Breadcrumbs.stories.tsx
- src/js/components/Breadcrumbs/Breadcrumbs.tsx
- src/js/components/Breadcrumbs/index.ts
- src/js/index.ts
Add the Breadcrumbs component into v4
> SO-4735-add-breadcrumbs-component

- package.json
- src/js/components/Pill/Pill.stories.tsx
- src/js/components/Pill/Pill.tsx
Updating the component to have the following options
* pass a custom `style` attribute
* pass custom classes via `mods` attribute
> Updating Pill to accept overrides

- package.json
Up the package number to correct version
> bump version for v4

- package.json
- src/js/components/Toolbar/Toolbar.stories.tsx
- src/js/components/Toolbar/Toolbar.tsx
Add ability to render children to Toolbar component and add story with breadcrumbs as Toolbar child component.
> SO-4735: Add ability to render children to Toolbar component

- package.json
- src/css/components/Nav.scss
- src/js/components/Nav/Nav.tsx
This PR is to fix bugs found in staging in regards to this ticket https://teamsnap.atlassian.net/browse/SO-4734.
- Added z-index for when overlay is open so that navigation is always on top.
- Removed hidden icon 
- Added max-width
> Minor fixes to Navbar found in staging

- package.json
- src/css/components/Nav.scss
- Added min and max width to navbar
- Made flyout link fullwidth
> SO-4734: Minor tweaks to navbar from staging tests

- package.json
- src/css/components/Nav.scss
- src/js/components/Nav/Nav.stories.tsx
- src/js/components/Nav/Nav.tsx
There was an issue with the Nav container when menu is opened with overlay the width would grow randomly. Also fixes some issues in classic where navigation wouldn't fix with text on smaller screens.
> SO-4734: More design fixes 

- package.json
- src/js/components/Breadcrumbs/Breadcrumbs.stories.tsx
- src/js/components/Breadcrumbs/Breadcrumbs.tsx
- src/js/components/Toolbar/Toolbar.stories.tsx
- src/js/components/Toolbar/Toolbar.tsx
Make the Breadcrumbs component more flexible by allowing users to simply pass in an array of links, text, or whatever and just render those out as breadcrumbs.
> So 4735 toolbars with breadcrumbs

- package.json
- src/css/components/Nav.scss
- src/css/components/Panel.scss
- src/js/components/Table/Table.stories.tsx
- src/js/components/Table/Table.tsx
https://teamsnap.atlassian.net/browse/SO-4897
> SO-4897: Remove hover state on non-sortable column headers

- netlify.toml
This is a fix for CORS errors showing up for fonts when importing teamsnap-ui scss.
> add netlify config with cors headers

- package.json
- src/css/components/Nav.scss
- src/js/components/Nav/Nav.stories.tsx
- src/js/components/Nav/Nav.tsx
- src/js/components/Skittles/Skittles.tsx
More updates to Navbar includes:
- Better visual Hierarchy. 
- Updated "Skittle" colors
- Selected item class. 
https://teamsnap.atlassian.net/browse/SO-4896
> SO-4896: Navbar Improvements II

- src/css/components/Nav.scss
- src/js/components/Nav/Nav.tsx
- src/js/components/Skittles/Skittles.tsx
Need to make sure nav item link color is white.
> SO 4896 remove consoles and update nav item color 

- src/js/components/Field/Field.tsx
- src/js/components/Table/Paginated/DateFilter.tsx
- src/js/components/Table/Paginated/PaginatedTable.stories.tsx
- src/js/components/Table/Paginated/PaginatedTable.tsx
- src/js/components/Table/Paginated/helpers.tsx
Created a date variant for PaginatedTable filters
Now user can filter by a range of dates or selecting specific years...
> So 4925 birthday filter

- package.json
- src/js/components/Toolbar/Toolbar.stories.tsx
- src/js/components/Toolbar/Toolbar.tsx
https://teamsnap.atlassian.net/browse/SO-5013
> SO-5013: Fix show admin conditional rendering

- package.json
- src/js/components/ComboBox/Combobox.tsx
- src/js/components/Table/Paginated/PaginatedTable.tsx
- yarn.lock
The combobox component did not have a way to set its state from a prop, so I've added that. Additionally, I've wired up the paginated table to read the value from the context for a given field to do just that :)
> Add support for setting combobox values from props

- package.json
- src/js/components/ComboBox/Combobox.tsx
This adds support for applying filters when clicking outside of the Flyout.
> apply filters for combobox on click outside of popup

- src/js/components/ComboBox/Combobox.tsx
- src/js/components/Table/Paginated/PaginatedTable.stories.tsx
- src/js/components/Table/Paginated/helpers.tsx
Sorting items for Table filters
Lowecase searchParam before searching for an item on combobox
> Sorting filter values

- package.json
- src/js/components/ComboBox/Combobox.test.tsx
- src/js/components/ComboBox/Combobox.tsx
- src/js/components/Table/Paginated/PaginatedTable.stories.tsx
- src/js/components/Table/Paginated/PaginatedTable.tsx
Currently the Combobox is calling the onChange function just when user clicks on "Filter" button to open up the filters section.
Expected behavior: onChange function should only be called when user clicks on "Done" or "Clear" button
> Combobox fix

- package.json
- src/js/components/ComboBox/Combobox.tsx
- src/js/components/InputControl/InputControl.tsx
- src/js/components/Table/Paginated/PaginatedTable.stories.tsx
- src/js/components/Table/Paginated/PaginatedTable.tsx
- src/js/components/Table/Paginated/helpers.tsx
Give the ability to access html as a label for combo box component.
> Checkbox label html

- src/css/components/Progress.scss
- src/js/components/ProgressBar/ProgressBar.stories.tsx
- src/js/components/ProgressBar/ProgressBar.tsx
- src/js/components/RadialProgress/RadialProgress.stories.tsx
> SO5218 modify progress bar not rounded and primary color

- package.json
- src/js/components/ComboBox/Combobox.tsx
- src/js/components/Table/Paginated/DateFilter.tsx
- src/js/components/Table/Paginated/PaginatedTable.stories.tsx
- src/js/components/Table/Paginated/PaginatedTable.tsx
- https://teamsnap.atlassian.net/browse/SO-4925 - Date filter fixes
- https://teamsnap.atlassian.net/browse/SO-5210 - One filter should be open at a time
- https://teamsnap.atlassian.net/browse/SO-5214 - "Clear" should clear out text box in combo box as well.
> Filters and DateFilter fixes

- package.json
- src/js/components/Button/Button.tsx
- src/js/components/ComboBox/Combobox.tsx
- src/js/components/Table/Paginated/PaginatedTable.tsx
> Add clear all button for filters

- package.json
- src/js/components/Table/Paginated/DateFilter.tsx
- src/js/components/Table/Paginated/PaginatedTable.stories.tsx
- src/js/components/Table/Paginated/PaginatedTable.tsx
- Fix empty filter when `[No Date]` is selected as date filter. 
- Make `noDateLabel` more generic.
> Fix [No Date] selection of DateFilter

- package.json
- src/assets/icons/check-circle-fill.svg
- src/css/components/SelectCard.scss
- src/css/components/index.scss
- src/js/components/Icon/Icon.stories.tsx
- src/js/components/SelectCard/SelectCard.stories.tsx
- src/js/components/SelectCard/SelectCard.tsx
- src/js/components/SelectCard/index.tsx
- src/js/icons/check-circle-fill.ts
https://user-images.githubusercontent.com/85572162/135907993-7beb06b3-3ea2-45c0-b9af-3ac6c2a2a5e3.mov
Reference of old changes:
https://user-images.githubusercontent.com/85572162/135534210-88c7f837-722b-4973-a343-d3674bda1a9c.mov
> SO 5231 create multi select card component

- package.json
Need to bump version for deploy
> Need to bump version for deploy

- package.json
- src/js/components/Drawer/Drawer.tsx
Fix mismatch between defaultProps and propTypes. Attach propTypes to Drawer component.
> fix(drawer component): fix issue with propTypes in the Drawer component

- src/css/components/Stepper.scss
- src/css/components/index.scss
- src/js/utils/easing.ts
Adding Stepper files in preparation for moving over `Stepper` and `Step` components from `teamsnap-spas`
> Adding Stepper.scss for future migration

- src/js/components/Table/Paginated/PaginatedTable.stories.tsx
- src/js/components/Table/Paginated/PaginatedTable.tsx
Add ability to provide a callback function for when a row is selected on paginated table. 
https://teamsnap.atlassian.net/browse/SO-5540
> Add callback row selected

- package.json
Need to update package number in order to publish code to npmjs. 
https://github.com/teamsnap/teamsnap-ui/commit/f79a174a1c843eca1b22682e6485283137089001
> Update package number

- src/css/components/Button.scss
- src/css/components/Checkbox.scss
- src/css/components/Combobox.scss
- src/css/components/Feedback.scss
- src/css/components/FieldGroup.scss
- src/css/components/Input.scss
- src/css/components/Progress.scss
- src/css/components/SelectBox.scss
- src/css/components/StepNav.scss
- src/css/components/SummaryList.scss
- src/css/config/config.scss
- src/js/non-component-stories/colors.stories.mdx
- Update color config to get rid of unused color variables
- Apply v4 color to color utility variables
- Update all components with correct variables
- Fix bug in color chart that had title out of sync with color
- Update design to more closely match Material icons
> Color updates

- package.json
- src/css/components/Popup.scss
- src/js/components/Popup/Popup.stories.tsx
- src/js/components/Popup/PopupTooltip.tsx
- src/js/components/Popup/index.ts
> SO-5525: New Popup tooltip component 

- .github/workflows/release.yml
- src/js/components/Icon/Icon.tsx
Need to see error logs to figure out what is the issue. Trying to do a dryrun of build and release"
> ci(release.yml): adding debugging to do dryrun

- .github/workflows/release.yml
Remove dryrun from release.yml
> fix(release.yml): remove dryrun

- package.json
trying to get the correct version going again so that we can have semantic releases again
> fix(package.json): correct version

- src/js/components/Popup/PopupTooltip.tsx
Adding the ability to modify the component through classes being passed to this new attribute
> feat(component): adding modify classes to component

- src/js/components/Popup/PopupTooltip.tsx
Adding ability to change the "highlight" color of the `PopupTooltip` text
> feat(component): adding attribute

- CODEOWNERS
This adds the CODEOWNERS file so that PRs will get automatically assigned to a review
If you feel like your team is the proper codeowner, then approve and merge this PR.
If you feel like your team is NOT the proper codeowner, comment back in the PR.
> [ISH-415] Add CODEOWNERS

- src/js/components/Table/Paginated/PaginatedTable.stories.tsx
- src/js/components/Table/Paginated/PaginatedTable.tsx
- src/js/utils/export.ts
This feature allows users to export all table data, respecting sorting and filtering in place.
RAP-565
> feat(paginatedtable component): add export table data functionality

- src/js/components/Table/Paginated/PaginatedTable.tsx
> fix(paginatedtable): change icon

- src/js/components/Table/Paginated/PaginatedTable.tsx
> feat(paginatedtable): add isLoading prop

- src/js/components/Table/Paginated/PaginatedTable.tsx
- src/js/components/Tabs/Tabs.stories.tsx
- src/js/components/Tabs/Tabs.tsx
Extended the tabs component so that content loads when change tables and not load all at once.
> Extend tabs component

- src/js/components/Table/Paginated/PaginatedTable.stories.tsx
> fix(paginated table): minor change to test auto deplou

- package.json
- src/js/components/Table/Paginated/BasicSearch.tsx
- src/js/components/Table/Paginated/PaginatedTable.stories.tsx
- src/js/components/Table/Paginated/PaginatedTable.tsx
- src/js/context/filterContext.ts
use basic search from outside the table
> feat(paginatedtable): use basic search from outside the table

- src/css/components/Popup.scss
- src/js/components/ComboBox/Combobox.stories.tsx
- src/js/components/ComboBox/Combobox.tsx
- src/js/components/Popup/PopupTooltip.tsx
- src/js/components/Table/Paginated/PaginatedTable.tsx
Give the ability to add tooltip to combo boxes
> feat(popuptooltip): added variant and tooltip featureAdd combobox tooltip

- src/css/components/Popup.scss
- src/js/components/ComboBox/Combobox.stories.tsx
- src/js/components/ComboBox/Combobox.tsx
- src/js/components/Table/Paginated/PaginatedTable.stories.tsx
- src/js/components/Table/Paginated/PaginatedTable.tsx
Make icon for tooltip clickable.
> fix(combox and paginatedtable): add ability to provide link for tooltip

- package.json
- src/js/components/Table/Paginated/PaginatedTable.tsx
pass some required params to filter context
> fix(paginatedtable): pass some required params to filter context

- src/css/components/Panel.scss
- src/js/components/Table/Paginated/PaginatedTable.stories.tsx
- src/js/components/Table/Paginated/PaginatedTable.tsx
- src/js/components/Table/Table.tsx
Remove hover state when rows aren't selected. Ability to click on anywhere on the row to select has
been added.
> fix(paginatedtable): remove hover state

- package.json
- src/js/components/ExpandableGroup/ExpandableGroup.stories.tsx
- src/js/components/ExpandableGroup/ExpandableGroup.tsx
- src/js/components/ExpandableGroup/index.ts
- src/js/index.ts
- yarn.lock
Adding `ExpandableGroup` component to be able to use different types of group contents with a  collapse-able option
> feat(component): adding component

- src/css/components/DateTimePicker.scss
Adding new `DateTimePicker` component
> feat(component): adding DateTimePicker

- src/css/components/DateTimePicker.scss
- src/js/components/DatePicker/DateTimePicker.tsx
Updating `datetime` type to allow for null or undefined values. This matches the definition of the selected property in the `ReactDatepicker` component
> fix(component): updating datetime types

- src/js/components/DatePicker/DateTimePicker.tsx
Re-adding some attributes for `ReactDatePicker`
> feat(component): re-adding attributes

- src/css/components/PasswordToggleInput.scss
- src/css/components/index.scss
- src/js/components/PasswordToggleInput/PasswordToggleInput.stories.tsx
- src/js/components/PasswordToggleInput/PasswordToggleInput.tsx
- src/js/components/PasswordToggleInput/index.ts
- src/js/index.ts
Creating new component that allows for toggling of the input type from text to password which allows for showing or hiding the password text
> feat(component): adding PasswordToggleInput component

- src/js/components/DatePicker/DateTimePicker.tsx
Updating the default value for `minDate` attribute so that we can see dates in the past if a `minDate` was not passed in or `startDate`
> fix(component): adding propert default for min date

- src/js/components/DatePicker/DateTimePicker.stories.tsx
Updating testcases for `DateTimePicker` component
> fix(file): updating testcases

- src/js/components/Toolbar/Toolbar.tsx
allow searchbar to be next to toolbar
> Fit toolbar search

- src/js/components/DatePicker/DateTimePicker.tsx
Adding ability for Birthdate field to display errors on blur
> feat(component): adding onBlur to datetime picker

- src/js/components/ComboBox/Combobox.stories.tsx
- src/js/components/ComboBox/Combobox.tsx
Updated combobox component to not show list of selected values as label when combobox is link
> feat(component): no label when combobox is link

- src/js/components/ComboBox/Combobox.stories.tsx
- src/js/components/ComboBox/Combobox.tsx
With custom search placeholder:
Default search placeholder:
> feat(component): Modify combobox to enable a custom search placeholder

- src/css/components/Popup.scss
- src/js/components/ComboBox/Combobox.tsx
- src/js/components/Popup/PopupAction.tsx
- src/js/components/Popup/PopupConfirm.tsx
- src/js/components/Popup/PopupTooltip.tsx
Fixed issue where pop-up code be hidden if parent container had overflow hidden. The components now also correctly remove event listeners.
> fix(pop-ups): fixed issues with overflow hidden for pop-ups

- src/js/components/Popup/Popup.stories.tsx
- src/js/components/Popup/PopupAction.tsx
* Using Functional component instead of class
* Using Typescript instead of prop-types
* Handling hover state using CSS instead of JS to avoid recreating components when the user hovers over popup actions
> Popup refactoring

- .github/workflows/main.yml
- .releaserc
- CONTRIBUTING.md
- README.md
With main as the default branch, update documenation and configuration to reflect the change
> ISH 1043 update v4 for main

- src/js/components/ExpandableGroup/ExpandableGroup.tsx
- src/js/components/ListToggle/ListToggle.tsx
isExpanded prop added to control expanded visual on initial render.
> feat(ListToggle): Add isExpanded prop

- src/js/components/Toolbar/Toolbar.tsx
This PR removes that little dot beside the icons
> show helpBody only when exists

- src/css/components/Combobox.scss
Add cursor effects when hovering over a ComboBox component.
https://teamsnap.atlassian.net/browse/B2B-382
> style(combobox.scss): add hover styles to ComboBox component

- src/css/components/Nav.scss
- src/js/components/Nav/Nav.tsx
Add ability to supply navigation a footer image to display at bottom of navigation
> B2B-967 - feat(nav): add ability add a footer image to navigation

- src/js/components/ExpandableGroup/ExpandableGroup.stories.tsx
- src/js/components/ExpandableGroup/ExpandableGroup.tsx
Making the delete option for `ExpandableGroup` component optional
> feat(component): making delete optional

- src/js/components/ExpandableGroup/ExpandableGroup.stories.tsx
- src/js/components/ExpandableGroup/ExpandableGroup.tsx
Add closed helper text to `ExpandableGroup`.
> B2B-1408 Closed Helper Text on Expandable Groups

- src/js/components/ExpandableGroup/ExpandableGroup.tsx
Changing the component to accept a hasError flag, which will open the panel when closed to inform users that we have an error
> feat(component): adding has error flag

- src/js/components/ExpandableGroup/ExpandableGroup.tsx
Add test id so that we can test. Hopefully this PR triggers new release
> feat(expandablegroup): add test id

- src/js/components/Table/Paginated/BasicSearch.tsx
> feat(basic search): add test id to input

- src/js/components/Table/Paginated/PaginatedTable.tsx
Organization frontend  integration test enhancements
> feat(PaginatedTable): Add Test IDs

- src/js/components/Panel/Panel.tsx
- src/js/components/Table/Paginated/DateFilter.test.tsx
- src/js/components/Table/Paginated/DateFilter.tsx
> fix otherProps error in the console
