- src/Button/Button.scss
- src/base/config.scss
- src/base/fonts/index.scss
- src/base/fonts/open-sans.scss
- src/base/index.scss
- src/base/typography.scss
- src/components/button.scss
- src/components/index.scss
- src/index.scss
This PR adds a directory structure seeded with some of the initial settings for defining components. The variables in `config` are pulled from Classic since all the themes are based on these names. The Button component kicks off a new [BEM naming convention](https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md).
I tried out including the variable `config.scss` in the `.Button` component. Let's see how that works out. We can modify if that doesn't seem right.
Some of the structure is built to facilitate the inclusion of this library as a submodule within the style guide. For example, adding `index`es within each directory and in the top level makes it easy to grab just one file for compilation in the style guide:
> Add initial structure and button component

- src/base/config.scss
For some reason webpack picks up colons in sass comments and fails due to a missing semicolon.
> fixes issue with comment breaking compile

- package.json
- src/utils/size.scss
The responsive sizing classes were not 'stacking' correctly, which caused them to override each other in the wrong order.
This fixes the class inheritance issue and modifies the size generator slightly, this modification adds Fit and Fill to the responsive sections as well as outputs a much smaller file footprint due to fewer media query declarations. 
The file is now organized by media query blocks, for example.
* Base Sizes, followed by Fit, Fill, Full
.u-size#{number}of#{number} {}
* Responsive Sizes, followed by Fit, Fill, Full for each size.
@media (min-width: #{value}) {
.u-#{size}-size#{number}of#{number} {}
}
> Fix a small bug in the size utility

- package-lock.json
- package.json
- src/components/Checkbox.scss
This fixes an issue where if the checkbox was checked by default the disabled style wasn't being applied.
> Checkbox specificity fix

- src/components/Input.scss
I noticed when Classic isn't loaded with TS-UI that `Input` was picking up user agent font styles. This sets the font size and family to ensure correct styling on the form.
> Add font characteristics

- package-lock.json
- package.json
- Fixes issue where compiled assets weren't properly being built before publish.
- Adds new `npm run deploy` script for ops to use when deploying to the cdn
- Bumps to 2.0.1
> Fixes compile scripts

- package.json
- src/css/utils/color.scss
- src/css/utils/space.scss
Adds utilities to support table header controls:
- grey color utility for $ts-grey @williamdingwall foreground/background/middleground were all too light or too dark. $ts-grey gets themed, right?
- negative margin utility for right-aligned sorting arrows
- Examples in UI-Patterns PR: https://github.com/teamsnap/ui-patterns/pull/45
> Add grey color utility and negative margin utility

- src/css/components/Button.scss
- src/css/components/ButtonGroup.scss
- src/css/components/Popup.scss
- src/css/components/index.scss
Includes modifiers for several popup positions:
- Default - up and centered
- Overlay - on top of the triggering element, no pointer
- Down - below the triggering element, centered by default
- Right - right-aligned with triggering element (can be combined with down modifier)
- Right Hang - hangs off the right side of an element. Useful for small buttons or icon buttons.
- Left - left-aligned with triggering element (can be combined with down modifier)
- Left Hang - hangs off the left side of an element. Useful for small buttons or icon buttons.
Two options for status buttons.
1. Button is neutral by default, and when hovered or `is-active` (as in ButtonGroup), it gets yes/no/maybe color
2. Button has yes/no/maybe color by default
Button intended for symbols or icons, has fixed width and …
> Add popup component and status buttons

- package.json
- src/css/components/FieldGroup.scss
When need to have the red border when validating textarea.
> Add textarea to is-notValid style class

- package-lock.json
- package.json
- src/css/fonts/museo.scss
- src/css/fonts/ss-pika.scss
Use absolute paths for TS-UI fonts
The way that TS-UI is used makes it difficult to use a relative font path, since the root URL changes depending on how it is imported into different apps. Fonts are on the CDN via TS-UI, so this grabs that location. Fonts don't really need to be versioned, but they are right now, so this uses one of the earlier versions and shouldn't need updated unless we change our font stack.
> Update font paths to use an absolute path to CDN

- CHANGELOG.md
- package.json
- src/css/fonts/museo.scss
- src/css/fonts/ss-pika.scss
I just noticed that the fonts weren't working in UI-Patterns with Classic CSS turned off. I only tested this locally on http, but it needs to work on https too. Using `//dugout` so it works for both, unless there is some better way to do this?
> Use // to work for both http and https

- CHANGELOG.md
- package-lock.json
- package.json
- src/css/fonts/museo.scss
- src/css/fonts/ss-pika.scss
The `//` method wasn't working on `go.teamsnap.com`, so updating to explicitly stating `https`.
> Update fonts to https

- src/css/components/Feedback.scss
Just a quick fix for this issue..
before:
after:
> making the feedback popup component more flexible

- src/js/components/Table/Table.js
adding a placeholder option to the table component for empty states
relates to https://teamsnap.atlassian.net/browse/TP-667
> adding a placeholder text option for empty tables

- src/css/components/Daypicker.scss
- src/css/themes/blue-steel.scss
- src/css/themes/care-bear.scss
- src/css/themes/christmas-sweater.scss
- src/css/themes/custom-aquablue.scss
- src/css/themes/custom-black.scss
- src/css/themes/custom-blue.scss
- src/css/themes/custom-darkblue.scss
- src/css/themes/custom-darkgreen.scss
- src/css/themes/custom-darkred.scss
- src/css/themes/custom-goldenyellow.scss
- src/css/themes/custom-gray.scss
- src/css/themes/custom-green.scss
- src/css/themes/custom-leafgreen.scss
- src/css/themes/custom-lemonyellow.scss
- src/css/themes/custom-lightblue.scss
- src/css/themes/custom-orange.scss
- src/css/themes/custom-pink.scss
- src/css/themes/custom-purple.scss
- src/css/themes/custom-red.scss
- src/css/themes/maple-leaf.scss
- src/css/themes/portland-oregon.scss
- src/css/themes/ranger-smith.scss
- src/css/themes/up-beet.scss
- src/css/utils/color.scss
- Adds background color utilities for main themed colors, positive, negative
- Adds background utility based off link color - provides a light bg for links
- Adds a foreground color utility for text on color
- Includes the link hover state in each theme, currently these are compiling with the default link color, so links hover to blue
- WIP - Adds initital styles for Daypicker component
> Add color utilities

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/css/components/Checkbox.scss
- src/css/components/FieldGroup.scss
- src/css/components/Input.scss
- src/css/components/SelectBox.scss
- src/css/components/StepNav.scss
- src/css/config/config.scss
- src/css/utils/border.scss
- src/css/utils/color.scss
- src/css/utils/display.scss
- src/css/utils/index.scss
- src/css/utils/max-width.scss
- src/css/utils/position.scss
- src/css/utils/space.scss
- src/css/utils/text.scss
Changes:
- Update `Checkbox`
- no markup changes
- Remove inner box shadows for cleaner appearance
- Change radio to standard circle-within-a-circle appearance and add animation
- Add hover states and change focus state (colored border)
- Use SVG for inner icons (check and lock)
- Add `--large` modifier
- Add `--pill` modifier for full-width, easily tappable radios
- Add `--colorPrimary` modifier for standard TS Blue version that is also themed
- Update `Input` and `SelectBox` to match above changes
- Remove inner shadow
- Change focus state to colored border (uses primary color)
- Update `StepNav`
- no markup changes
- Add `--xsmall` modifier
- Add support for numbers instead of SVG
- Reorganize CSS to remove repetition of size properties so modifiers can easily be created and size …
> WIP - Invitations updates

- CHANGELOG.md
- package.json
- src/css/components/Modal.scss
- src/css/components/index.scss
- src/css/config/config.scss
- src/css/config/themes/league.scss
- src/css/themes/league.scss
Adding html & css for modals. This should work with https://github.com/teamsnap/classic/blob/master/app/assets/javascripts/new-skin/ts-modal.js
also added some styling  variation which can be turned on in theme settings
----
Note: this was being held off on to pair with the react component, but could be used in classic with the freemium test, and other areas. Also sounds like there might never be a react component for this since state might be managed in a number of different ways.
> DES-56 - Add Modal CSS

- src/css/components/Checkbox.scss
Add design for checkbox version of `Pill` modifier:
> Add reduced radius for pill with checkbox

- src/js/components/Table/Table.tsx
Trying to get TeamSnap UI ready for React 17+.
I think this is the only component with deprecated lifecycle methods. ![](https://media3.giphy.com/media/JMV7IKoqzxlrW/giphy.webp?cid=790b76113a7fd8c3480e2d61e58c79e969eca3d9703472b8&rid=giphy.webp)
So this PR removes those lifecycle methods in favor of the alternatives proposed in https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#updating-state-based-on-props
> Remove deprecated lifecycle method for prep for react 17

- package-lock.json
- src/css/config/themes/blue-steel.scss
- src/css/config/themes/care-bear.scss
- src/css/config/themes/christmas-sweater.scss
- src/css/config/themes/custom-aquablue.scss
- src/css/config/themes/custom-black.scss
- src/css/config/themes/custom-blue.scss
- src/css/config/themes/custom-darkblue.scss
- src/css/config/themes/custom-darkgreen.scss
- src/css/config/themes/custom-darkred.scss
- src/css/config/themes/custom-goldenyellow.scss
- src/css/config/themes/custom-gray.scss
- src/css/config/themes/custom-green.scss
- src/css/config/themes/custom-leafgreen.scss
- src/css/config/themes/custom-lemonyellow.scss
- src/css/config/themes/custom-lightblue.scss
- src/css/config/themes/custom-orange.scss
- src/css/config/themes/custom-pink.scss
- src/css/config/themes/custom-purple.scss
- src/css/config/themes/custom-red.scss
- src/css/config/themes/league.scss
- src/css/config/themes/maple-leaf.scss
- src/css/config/themes/portland-oregon.scss
- src/css/config/themes/ranger-smith.scss
- src/css/config/themes/up-beet.scss
This change is required to resolve an indirect pathing problem I ran into while trying to utilize the league them in organization-frontend. The theme in question was attempting to import `../config/index` which took us one level too far out of the file tree structure and therefore it was unable to resolve the path. Upon further investigation, it was discovered this path was actually incorrect for every theme in the config directory.
> fix import path for config index

- src/js/components/Popup/PopupConfirm.tsx
Fix memory leaks from occurring, when clicking outside the `<PopupConfirm />` component
The memory leaks resulted when the following scenarios occurred:
- Popup component is first toggled off, then toggled back on
- Popup component is no longer being rendered, and then a click event happens
In both cases, the `isPopupOpen` state was trying to update during the click event, but the component wasn't being rendered.
This is tested in both Storybook (component continues to work as before), and in the project where this component is being implemented (errors are no longer being logged).
> Fix PopupConfirm memory leaks

- CHANGELOG.md
- package-lock.json
- package.json
- src/js/components/Table/Table.tsx
This PR fixes an issue where the table would fail to render if you provided a default sort that was not one of the column names.
Tested locally against storybook.
> Fix bug where providing a nonexistent default sort would cause table to explode

- scripts/gulpfile.js
CSS nano tries to be clever by setting `z-index` to their minimum values based on all the values included in the CSS compile. We don't want that since we have other non-TS-UI z-indexes to deal with.
https://medium.com/@barvysta/naughty-cssnano-or-how-to-save-your-z-indexes-from-being-restructured-a42c2ab4241f
> Disallow CSSNano from messing with z-index

- CHANGELOG.md
- package-lock.json
- package.json
- src/css/utils/space.scss
- src/js/components/Table/Paginated/PaginatedTable.stories.tsx
- src/js/components/Table/Paginated/PaginatedTable.tsx
- src/js/components/Table/Paginated/PaginationButtons.tsx
- src/js/components/Table/Paginated/PaginationCurrentSubsetDisplay.tsx
- src/js/components/Table/Paginated/PaginationSelect.tsx
- src/js/components/Table/Paginated/helpers.tsx
- src/js/components/Table/Paginated/index.ts
- src/js/components/Table/Table.tsx
- src/js/components/Table/index.ts
This PR adds in a table that has wired up pagination controls and works with asynchronous data. This seems to be a common theme with several of our frontend applications, and the current table's sorting doesn't play nicely with paginated data, so this is an attempt to help remedy that situation by providing an easy to use solution.
> Add in opinionated pagination table

- CHANGELOG.md
- package-lock.json
- package.json
- src/css/components/Progress.scss
- src/js/components/ProgressBar/ProgressBar.stories.tsx
- src/js/components/RadialProgress/RadialProgress.stories.tsx
> adding an orange modifier to progress bars

- CHANGELOG.md
- package-lock.json
- package.json
- src/js/components/PanelBody/PanelBody.tsx
- src/js/components/PanelCell/PanelCell.tsx
- src/js/components/PanelRow/PanelRow.tsx
- src/js/components/Table/Table.tsx
Add aria roles to divs for tables. Div elements are arranged to show tabular data, and aria roles are added to appropriate Panel components.
Note that this assumes that the `PanelRow` will always be used as a table row, and that the `PanelCell` will always be used as a table cell. The `PanelBody` takes an optional `role` prop - it does not currently assume that its role will always be a table.
Closes #193
> Add aria roles for table

- CHANGELOG.md
- package-lock.json
- package.json
- src/js/components/Table/Table.tsx
This probably should have been this way to begin with when i originally added the custom sort function.
If you have/call the custom sort function, don't try to inline sort the table's contents, too.
> Delegate tables custom sort to custom sort fn

- CHANGELOG.md
- package-lock.json
- package.json
- src/js/components/Popup/PopupAction.tsx
This is intended behavior but currently wasn't working as intended.
> fix: Make popup-action stay open when clicked

- CHANGELOG.md
- package-lock.json
- package.json
- src/js/components/Popup/Popup.stories.tsx
- src/js/components/Popup/PopupConfirm.tsx
Make the popup confirm component more flexible by supporting extra classes, variable button text and adding direction. I added defaults for all the old static properties so it shouldn't impact components in the wild.
> Make popup more flexible

- package.json
- src/css/components/Nav.scss
- src/css/components/Toolbar.scss
- src/css/components/index.scss
- src/css/utils/flex.scss
- src/js/components/Toolbar/Toolbar.stories.tsx
- src/js/components/Toolbar/Toolbar.tsx
- src/js/components/Toolbar/index.ts
Icons are temporary until we replace Pika with whatever icon set we're using for v4.
> add in toolbar for alphav4

- package.json
- src/css/utils/color.scss
When importing our themes into .scss that ultimately gets shoveled into a postcss loader, we're seeing issues with our dynamic function lookup. This PR modifies that so that the dynamic function lookup is inlined (adds a few extra lines) but works with PostCSS loaders.
Here was the original stacktrace that caused this:
```
./src/styles/main.module.scss (../node_modules/css-loader/dist/cjs.js??ref--5-oneOf-7-1!../node_modules/postcss-loader/src??postcss!../node_modules/resolve-url-loader??ref--5-oneOf-7-3!../node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-7-4!./src/styles/main.module.scss)
SassError: Function not found: color-primary
on line 7 of ../node_modules/@teamsnap/teamsnap-ui/src/css/utils/color.scss, in function `get-function`
from line 7 of …
```
> Adjust color generation to play nicely with postcss imports

- CHANGELOG.md
- package.json
- src/js/components/Table/Table.tsx
Adjust table sort to spans as they shouldnt be links and buttons created weird behavior.
> Adjust table sort tags to spans

- src/css/components/Button.scss
- src/css/components/Nav.scss
- src/css/components/Panel.scss
- src/css/components/Tabs.scss
- src/css/components/Toolbar.scss
- src/css/config/config.scss
- src/css/config/themes/league.scss
These changes stem from: https://teamsnap.atlassian.net/browse/SO-4191
Here's some context behind a few of the changes:
**Restore base font size to panels**
I'm reverting the larger font sizes until we can apply it to more of the app. Right now, we have an inconsistent mix of 13-16px appearing in the body.
**Remove negative button style**
Cancel buttons should appear more neutral. So until we can change the markup across the app, I removed the `negative` button style.
> SO-4191 Misc style updates

- package.json
TeamSnap UI needs to specify react as a peer dependency. Yarn 2 throws errors around this, but this extra level of declaration can help any consumer of TeamSnap UI.
> Add peer dependencies for react

- package.json
- src/js/components/Table/Paginated/PaginatedTable.tsx
This PR is related to...
- [https://teamsnap.atlassian.net/browse/SO-4319](url)
It is adding the ability to use a previously created attribute in `PaginatedTable` to pass a custom filter component
> Adding custom filters for paginated table component

- CHANGELOG.md
- package-lock.json
- package.json
- src/js/components/Table/Paginated/PaginatedTable.tsx
Small tweak to alignment in pagination placement to center elements as a group. To better match mockup in: https://teamsnap.atlassian.net/browse/SO-4361
before
after
top placement before
top placement after (no changes)
> center all elements of bottom pagination

- package.json
- src/css/components/Nav.scss
- src/js/components/Nav/Nav.tsx
**Story / Task Link**
https://teamsnap.atlassian.net/browse/SO-4680
This increases the click area for opening the nav flyout.
https://user-images.githubusercontent.com/1085718/119859893-cc566600-bee3-11eb-9b9a-c3d2f2bd1d5f.mov
- Moved the onClick event to the Nav-header element.
- Added CSS for hover state.
> Increase click area on nav header

- package.json
- src/js/components/ToggleCheckboxList/ToggleCheckboxList.tsx
Updating field names to have a proper name rather than `name="Sample"` as well as adding deselect all functionality to select all button
> Updating field names for SO-4665 bug

- package.json
- src/css/components/Nav.scss
As requested in https://teamsnap.atlassian.net/browse/SO-4734 the width the the side nav should be bigger. Previous additions to TeamSnap UI didn't include this.
> SO-4734: More Navbar Improvements

- src/css/components/SelectBox.scss
Additionally, changing the color determination to use the color functions provided by v4 instead of the variable value.
> minor color changes to make disabled selects more readable

- package.json
- src/css/components/Nav.scss
- src/js/components/Nav/Nav.tsx
Found a bug on the collapsed menu where the arrow still shows and still able to open "organization" menu. 
I've removed the caret and the ability to view the "organizations" menu when the menu is collapsed.
> SO-4734: Fixed collapsed menu

- package.json
- src/js/components/Table/Paginated/PaginatedTable.tsx
Used `u-padBottomNone` to remove the padding applied from checkbox class. Opted to use utility class rather than using `isInline` prop due to some alignment issues within the table.
> SO-4786: Fix spacing of paginated tables. 

- package.json
- src/js/components/Table/Paginated/PaginatedTable.tsx
Missed a checkbox that needs `u-padBottomNone` class.
> SO-4786: Remove padding on all checkbox

- package.json
- src/css/components/Popup.scss
- src/js/components/Popup/Popup.stories.tsx
- src/js/components/Popup/PopupAction.tsx
In safari users are unable to hover over popup menu. For some reason users are also unable to click to button to keep popup menu open.
I've also added a few stories and also corrected some styling for the arrows. `leftHang` and `left` as well as `rightHang` and right were exactly the same thing.
"Hang"
"No Hang"
https://teamsnap.atlassian.net/browse/SO-5028
> SO-5028: Fix some issues with popup component. 

- src/js/components/Table/Paginated/PaginatedTable.tsx
- src/js/components/Table/Paginated/helpers.tsx
This PR fixes an issue where the paginated table's clear all would not fully update the DOM. I believe this is an issue where the context was getting the correct value but the DOM was not fully seeing the changes. The changes added regarding the `isResettingFilters` call help resolve this issue. It feels little wonky to me, and would love suggestions or feedback if you all have any :)
Also, did a small bit of cleanup and refactoring to help make sure this file is easier to understand. We can probably do more here as well.
> Fix issue where clear all would not fully udpate the dom, minor refactor

- package.json
- src/js/components/Checkbox/Checkbox.tsx
- src/js/components/CheckboxPill/CheckboxPill.tsx
- src/js/components/Field/Field.stories.tsx
- src/js/components/Field/Field.tsx
- src/js/components/Input/Input.tsx
- src/js/components/InputControl/InputControl.tsx
- src/js/components/Radio/Radio.tsx
- src/js/components/Toggle/Toggle.tsx
Currently, Checkbox and Radio components use the name property as the HTML ID attribute. It's common
for those elements to share a name but have unique IDs. This commit adds that functionality.
> Add id props for form input components

- package.json
The version on the v4 branch is 90 while the version on NPM is 92. This change puts them back into
sync
> fix: change the package version to match what is on NPM

- package.json
- src/js/components/Pill/Pill.tsx
Address issue with TypeScript complaining about passing in the event object when the onChange
handler does not specify any arguments.
RAP-182
> fix(pill component): add event parameter to onChange handler signature type

- src/js/components/Field/Field.tsx
Using "radio" as a type option on the Field component was raising warnings in the console. This addresses that issue.
> fix(field component): add 'radio' as an option for the field component's type prop

- package.json
Bumping versions because cz was not used
> Updating version to 108

- src/css/components/Checkbox.scss
I recently updated the checkbox design and the percent positioning of the checkbox must not have been hitting a solid pixel value because it was moving around a bit dependent on browser size.
This updates to calculate size and position in pixels based on the overall size of the checkbox so positioning should be consistently correct.
Before:
After:
> fix(checkbox): Update size to use pixel dimensions

- src/css/components/Stepper.scss
- src/css/fonts/index.scss
- src/css/teamsnap-ui.scss
- src/js/components/Popup/PopupTooltip.tsx
This is not ideal, but it was the only way I was able to get the paths working. Relative paths are modified in the node module but not in the local instance, breaking either storybook or the referencing project. This skirts the issue by not nesting the font reference so the relative path stays the same. I'm sure there is a way to fix this with settings in the sass process, but I didn't have the time to go there today.
FYI I did figure out that `yalc` works like a charm for linking TS-UI into teamsnap-spas, so I was able to test solutions in Storybook and Registration Frontend at the same time.
> Move fonts into main file to fix paths issue

- src/js/components/Button/Button.stories.tsx
- src/js/components/Loader/Loader.stories.tsx
- src/js/components/Loader/Loader.tsx
Adding custom size attribute to allow better composition. As you can see in the screenshot below, we can not manipulate the size of the animations
> feat(component): adding size attribute

- src/css/components/DateTimePicker.scss
Fixing issue with `DateTimePicker` pop up arrow displaying in the wrong place
> fix(component): fixing issue with location of pop up arrow

- src/js/components/Popup/Popup.stories.tsx
- src/js/components/Popup/PopupAction.tsx
Modified Popup Actions component to handle origin button styles customization.
> feat(component): modified Popup Action to have customized button

- .github/workflows/release.yml
- The node version number of the last successful build is different from the most current broken build. Changing the version number to point to 16 specifically.
> RAP-1187: Debug TeamSnap UI Release

- src/js/components/ExpandableGroup/ExpandableGroup.tsx
Prop isExpanded has been added to allow placement of new ExpandableGroup components to default open.
"fix #RAP-1038"
> feat(expandablegroup): add prop to allow default expansion

- src/js/components/Tabs/Tabs.tsx
Allow Tabs component to accept activeIndex prop to determine initial rendering.
re https://teamsnap.atlassian.net/browse/RAP-1216
> feat(tabs.tsx): add activeIndex prop to Tabs component

- package.json
- yarn.lock
When I updated several packages, I also update TypeScript by a few minor versions - it is rare, but this caught a bug with a new TypeScript version. [TypeScript 4.9](https://github.com/microsoft/TypeScript/releases/tag/v4.9.3) introduced a change that altered how dynamic imports worked (see attached screenshot for the issue in the changelog for TS 4.9). [This change](https://github.com/microsoft/TypeScript/pull/49663), cause dynamic imports to be transpiled from:
```js
Promise.resolve().then(function () { return require(x); })
```
to
```js
(_a = x, Promise.resolve().then(() => require(_a))
```
When transpiling to a CommonJS module format, which we are doing. This is a problem, because while Webpack tree-shaking can determine asset relevance in the first example, it cannot in the second. …
> fix: downgrade typescript to fix dynamic import issue

- src/js/components/Avatar/Avatar.stories.tsx
Assets have moved to GCS, updating reference for logo
> feat: [PLAT-2922] reference GCS instead of rackspace

- src/js/components/Field/Field.tsx
- src/js/components/ToggleCheckboxList/ToggleCheckboxList.tsx
This change is being made to remove typescript warnings/ errors that are showing up during unit test execution
This will lead to a 33% reduction in error messages from roughly 7400 lines to 4900
> refactor(component): adding onChange event to prevent typescript errors

- src/js/components/Field/Field.tsx
Adding `text` type to the `type` attribute in order to avoid console errors for when trying to use the type text which is a valid input option
> feat(component): adding text option for Field component

- src/js/components/ComboBox/Combobox.tsx
Adding on hover state text so we can hint that a `ComboBox` is reliant on another As per [B2B-1625](https://teamsnap.atlassian.net/browse/B2B-1625) 
[B2B-1625]: https://teamsnap.atlassian.net/browse/B2B-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(component): adding OnHoverText option
